### ISSUE TITLE
module does not support bower install and and loading

### ISSUE THREAD

**Issue by artemkaint** [jeresig/i18n-node-2#41]
module has not valid  bower.json file and universal amd load (e.x. requirejs for browser)

**Comment by MaffooBristol** [comment]
This is purely a nodejs module, but I agree that it would be nice if it could be polymorphic.

You'd have a to find a browser-based version of sprintf in order to get it to work, also a lot of the functionality such as automatically writing to the language file when it encounters a new phrase wouldn't work out of the box on the client.

tl;dr - it's a node module.

**Comment by gjuchault** [comment]
@MaffooBristol  is right.
